---

- hosts: all
  gather_facts: true
  vars:
      benchmark:
          name: "{{ 'CIS Amazon Web Services Foundations Benchmark' | replace(' ','_') }}"
          version: 1.4.0
          profile: "{{ }}"
  become: false
  collections:
      - azure.azcollection
      - ansible.posix
  roles:
      - role: "{{ playbook_dir }}"
        system_is_container: "{{ is_container | default(false) }}"
