---
- name: PREREQ | Import the Microsoft repository key
  rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc
  changed_when: false
  become: yes

- name: PREREQ | Create local azure-cli repository information.
  copy:
    dest: "/etc/yum.repos.d/azure-cli.repo"
    content: |
      [azure-cli]
      name=Azure CLI
      baseurl=https://packages.microsoft.com/yumrepos/azure-cli
      enabled=1
      gpgcheck=1
      gpgkey=https://packages.microsoft.com/keys/microsoft.asc
  changed_when: false
  become: yes

- name: PREREQ | Yum Installs
  yum:
    name: "{{ packages }}"
    state: present
  become: yes
  changed_when: false
  vars:
    packages:
    - unzip
    - jq

- name: PREREQ | Install Python Packages
  pip:
    name: jmespath
  become: yes

- name: PREREQ | Download and install AWS CLI
  block:
  - name: PREREQ | Create AWS CLI runway folder
    file:
      path: "{{ aws_cli_runway_path }}/extracted"
      state: directory

  - name: See if AWS CLI already exists
    stat: path={{ aws_cli_runway_path }}/awscliv2.zip
    register: zip_path

  - name: PREREQ | Download AWS CLI
    get_url:
      url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64-2.2.8.zip
      dest: "{{ aws_cli_runway_path }}/awscliv2.zip"
      mode: '0440'
    when: not zip_path.stat.exists

  - name: PREREQ | Extract AWS CLI
    ansible.builtin.unarchive:
      src: "{{ aws_cli_runway_path }}/awscliv2.zip"
      dest: "{{ aws_cli_runway_path }}/extracted"
    when: not zip_path.stat.exists

  - name: PREREQ | Execute AWS CLI install script
    command: "{{ aws_cli_runway_path }}/extracted/aws/install --bin-dir {{ local_bin_dir }}"
    changed_when: false
    become: yes

