---
- name: Gather distribution info
  setup:
      gather_subset: distribution,!all,!min
  when:
      - ansible_distribution is not defined
  tags:
      - always

- name: Check ansible version
  ansible.builtin.assert:
      that: ansible_version.full is version_compare( ansible_min_version, '>=')
      fail_msg: You must use ansible {{ ansible_min_version }} or greater
      success_msg: Ansible version is supported
  tags:
      - always

# - name: Check AWS variable have been added
#   ansible.builtin.assert:
#     that:
#       - aws_user.access_key_id is defined
#       - aws_user.secret_access_key
#       - aws_default_region
#     fail_msg: Please ensure that all aws user variables have been set
#     success_msg: AWS user settings are set
#   tags:
#       - always

- name: Run Prerequisites
  ansible.builtin.import_tasks: prereqs.yml
  when: check_prereqs
  tags:
      - prereqs

- name: Run Section 1 tasks
  ansible.builtin.import_tasks: section_1/main.yml
  when: awscis_section1
  tags:
      - section1

- name: Run Section 2 tasks
  ansible.builtin.import_tasks: section_2/main.yml
  when: awscis_section2
  tags:
      - section2

- name: Run Section 3 tasks
  ansible.builtin.import_tasks: section_3/main.yml
  when: awscis_section3
  tags:
      - section3

- name: Run Section 4 tasks
  ansible.builtin.import_tasks: section_4/main.yml
  when: awscis_section4
  tags:
      - section4

- name: Run Section 5 tasks
  ansible.builtin.import_tasks: section_5/main.yml
  when: awscis_section5
  tags:
      - section5

- name: Post
  ansible.builtin.import_tasks: post.yml
